/* Visual-only workout controls. Exercises and log semantics remain in App/Store. */
'use strict';
window.WorkoutCockpit={
 current:null,paused:false,celebrationTimer:null,
 map(session,index){return `<nav class="cockpit-map" aria-label="Workout exercise progress">${session.exercises.map((e,i)=>{const done=e.sets.filter(s=>s.done).length,state=e.skipped?'skipped':done===e.sets.length?'complete':i===index?'current':done?'partial':'pending';return `<button type="button" data-action="cockpit-jump" data-index="${i}" class="cockpit-map-item ${state}" ${i===index?'aria-current="step"':''} aria-label="${App.esc(e.name)}, ${state}, ${done} of ${e.sets.length} sets"><span>${state==='complete'?'✓':state==='skipped'?'−':i+1}</span><strong>${App.esc(e.name)}</strong><small>${e.skipped?'Skipped':`${done}/${e.sets.length} sets`}</small></button>`;}).join('')}</nav><p class="small cockpit-key">Green: complete · orange: current · dashed: skipped. Tap an exercise to jump.</p>`;},
 demo(id){const assets=ExerciseDemos.assets(id);if(!assets.length)return '<p class="small">No animation for this exercise. Open Guide for its technique.</p>';return `<div class="cockpit-demo" data-exercise="${App.esc(id)}">${assets.length>1?`<label>Movement<select data-cockpit-demo-choice>${assets.map(a=>`<option value="${App.esc(a.id)}">${App.esc(a.name)}</option>`).join('')}</select></label>`:''}<img data-cockpit-image src="${App.esc(assets[0].poster)}" alt="${App.esc(assets[0].name)} — movement reference" width="600" height="600"><div class="row wrap"><button type="button" data-action="cockpit-demo-toggle" class="small-btn">${this.paused||matchMedia('(prefers-reduced-motion: reduce)').matches?'Play animation':'Pause animation'}</button><p class="small" data-cockpit-demo-status></p></div></div>`;},
 steppers(e){return `<div class="cockpit-steppers" aria-label="Adjust this set">${[['weight','Weight',e.increment],['reps','Reps',1],['rir','RIR',0.5]].map(([field,label,step])=>`<div><span>${label}</span><div>${[-1,1].map(dir=>`<button type="button" class="small-btn" data-action="cockpit-adjust" data-field="${field}" data-delta="${step*dir}" aria-label="${dir>0?'Increase':'Decrease'} ${label.toLowerCase()}" ${e.skipped?'disabled':''}>${dir>0?'+':'−'}</button>`).join('')}</div></div>`).join('')}</div>`;},
 timer(){return `<div class="cockpit-rest"><div class="cockpit-rest-ring" id="cockpitRestRing" role="progressbar" aria-label="Rest time remaining"><div><strong id="timerDisplay">${Timer.format(Timer.remaining)}</strong><span id="cockpitRestState" role="status" aria-live="polite">Ready</span></div></div><div><p class="small" id="cockpitRestLabel">${App.esc(Timer.activeLabel||'Rest timer')}</p><div class="row wrap">${App.button(Timer.interval?'Pause rest':'Start rest','timer-guided-toggle','id="guidedTimerToggle"','small-btn')}${App.button('+15 sec','timer-add','data-seconds="15"','small-btn')}${App.button('Skip rest','cockpit-rest-skip','','small-btn')}</div></div></div>`;},
 updateTimer(){const ring=document.getElementById('cockpitRestRing');if(!ring)return;const total=Math.max(1,Timer.duration),remaining=Math.max(0,Timer.remaining),value=Math.min(1,remaining/total);ring.style.setProperty('--rest-progress',`${value*100}%`);ring.classList.toggle('rest-complete',!!Timer.completed);ring.setAttribute('aria-valuemin','0');ring.setAttribute('aria-valuemax',String(Math.max(total,remaining)));ring.setAttribute('aria-valuenow',String(remaining));const state=Timer.completed?'Rest complete — next set':Timer.interval?'Resting':Timer.remaining===0?'Ready for next set':Timer.remaining<Timer.duration?'Paused':'Ready';const label=document.getElementById('cockpitRestState');if(label.textContent!==state)label.textContent=state;document.getElementById('cockpitRestLabel').textContent=Timer.activeLabel||'Rest timer';},
 mount(){const map=document.querySelector('.cockpit-map'),selected=map?.querySelector('[aria-current]');if(selected)map.scrollLeft+=selected.getBoundingClientRect().left-map.getBoundingClientRect().left-(map.clientWidth-selected.offsetWidth)/2;const root=document.querySelector('.cockpit-demo');if(root){const assets=ExerciseDemos.assets(root.dataset.exercise);this.current={root,assets,asset:assets[0],image:root.querySelector('[data-cockpit-image]')};root.querySelector('[data-cockpit-demo-choice]')?.addEventListener('change',event=>{if(this.current?.root!==root)return;this.stop();this.current.asset=assets.find(a=>a.id===event.target.value)||assets[0];this.syncDemo();});this.syncDemo();}const zone=document.querySelector('.cockpit-swipe-zone');if(zone){let start=null;zone.addEventListener('pointerdown',e=>{start=null;if(e.target.closest('button,input,select,textarea,a,summary'))return;start={x:e.clientX,y:e.clientY};});zone.addEventListener('pointercancel',()=>start=null);zone.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)this.move(dx<0?1:-1);});}this.updateTimer();},
 syncDemo(){const c=this.current;if(!c||!c.root.isConnected)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(document.hidden||document.querySelector('.forge50-guide-modal.open')||this.paused||reduced&&!this.motionApproved){this.stop();return;}if(c.image.getAttribute('src')===c.asset.gif)return;c.image.onload=()=>{if(this.current===c)c.root.querySelector('[data-cockpit-demo-status]').textContent='Movement reference · Guide has form cues.';};c.image.onerror=()=>{if(this.current!==c)return;c.image.onerror=c.image.onload=null;c.image.src=c.asset.poster;c.root.querySelector('[data-cockpit-demo-status]').textContent='Animation unavailable. Open online once to cache it, or use Guide.';};c.image.src=c.asset.gif;c.root.querySelector('[data-cockpit-demo-status]').textContent='Loading movement…';},
 stop(){const c=this.current;if(!c)return;c.image.onerror=c.image.onload=null;c.image.src=c.asset.poster;c.root.querySelector('[data-cockpit-demo-status]').textContent=this.paused?'Animation paused.':'Movement reference';},
 dispose(){this.stop();this.current=null;},
 toggleDemo(){this.paused=matchMedia('(prefers-reduced-motion: reduce)').matches&&!this.motionApproved?false:!this.paused;this.motionApproved=true;if(this.paused)this.stop();else this.syncDemo();const button=this.current?.root.querySelector('[data-action="cockpit-demo-toggle"]');if(button)button.textContent=this.paused?'Play animation':'Pause animation';},
 move(direction){const s=Store.session(App.activeId);if(!s)return;let index=App.guidedExerciseIndex+direction;while(index>=0&&index<s.exercises.length&&s.exercises[index].skipped)index+=direction;if(index>=0&&index<s.exercises.length)App.run(()=>App.action('cockpit-jump',{dataset:{index:String(index)}}));},
 adjust(field,delta){const input=document.querySelector(`.guided-set [data-set-field="${field}"]`);if(!input||input.disabled||!['weight','reps','rir'].includes(field)||!Number.isFinite(delta))return;const e=Store.session(App.activeId)?.exercises[App.guidedExerciseIndex],base=input.value!==''?Number(input.value):field==='reps'?Number(e.reps.split('-')[0])-Math.sign(delta):0;const value=Math.max(Number(input.min),Math.min(Number(input.max),Math.round((base+delta)*100)/100));input.value=String(value);input.dispatchEvent(new Event('input',{bubbles:true}));},
 celebrate(name){document.getElementById('cockpitCelebration')?.remove();clearTimeout(this.celebrationTimer);const element=document.createElement('div');element.id='cockpitCelebration';element.className='cockpit-celebration';element.setAttribute('role','status');element.innerHTML=`<strong>★ Personal record</strong><span>${App.esc(name)}</span><button type="button" aria-label="Dismiss personal record" class="small-btn">×</button>`;element.querySelector('button').onclick=()=>element.remove();document.body.append(element);this.celebrationTimer=setTimeout(()=>element.remove(),3500);},
 recap(s){const count=App.count(s);const records=s.exercises.filter(e=>{const sets=e.sets.filter(x=>x.done);if(!sets.length)return false;const previous=Store.state.sessions.filter(x=>x.id!==s.id&&x.type==='lifting'&&!x.legacy&&(x.date<s.date||x.date===s.date&&Store.state.sessions.indexOf(x)<Store.state.sessions.indexOf(s))).flatMap(x=>x.exercises.filter(y=>y.id===e.id&&y.weightMode===e.weightMode).flatMap(y=>y.sets.filter(z=>z.done)));if(!previous.length)return false;const best=previous.sort((a,b)=>b.weight-a.weight||b.reps-a.reps)[0];return sets.some(x=>x.weight>best.weight||x.weight===best.weight&&x.reps>best.reps);});return `<section class="card cockpit-recap"><p class="eyebrow">WORKOUT SAVED</p><h2>${s.partial?'Every logged set counts':'Session complete'}</h2><div class="metric-grid"><div><strong>${count.done}</strong><span>Sets logged</span></div><div><strong>${records.length}</strong><span>Record exercises</span></div><div><strong>${Math.max(0,s.duration||0)}</strong><span>Minutes</span></div></div><p class="small">${count.total-count.done} planned sets unlogged. Skipped and optional sets stay unlogged.</p>${records.length?`<p>★ ${records.map(e=>App.esc(e.name)).join(', ')}</p>`:'<p class="muted">Your work is saved. Review the comparisons below for progress.</p>'}${App.button('See next-session targets','cockpit-next-coach','','secondary-btn')}</section>`;}
};
document.addEventListener('visibilitychange',()=>WorkoutCockpit.syncDemo());
document.addEventListener('click',()=>setTimeout(()=>WorkoutCockpit.syncDemo(),0));
document.addEventListener('keydown',e=>{if(e.key==='Escape')setTimeout(()=>WorkoutCockpit.syncDemo(),0);});
