// Optional: npm install playwright && npx playwright install chromium
// Run: node tests/browser.test.cjs
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..');let updateVersion=false;
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);let file=path.join(root,pathname==='/'?'index.html':pathname);if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');let content=fs.readFileSync(file);if(updateVersion&&file.endsWith('/sw.js'))content=Buffer.from(content.toString().replace('v2.4.0-muscle-guides','v2.4.0-muscle-guides-test-update'));res.setHeader('Content-Type',types[path.extname(file)]||'text/plain');res.setHeader('Cache-Control','no-store');res.end(content);});
let browser,checks=0;const errors=[];
const pass=name=>{checks++;console.log('PASS',name);};
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,...(process.env.FORGE_BROWSER_PATH?{executablePath:process.env.FORGE_BROWSER_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--use-gl=angle','--use-angle=swiftshader']});
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(url);await page.waitForSelector('[data-action="start"]');assert.equal(await page.locator('h1').innerText(),'Your training, your rhythm.');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);pass('mobile home loads without horizontal overflow');
 await page.screenshot({path:process.env.FORGE_SCREENSHOT_DIR?process.env.FORGE_SCREENSHOT_DIR+'/home.png':'/tmp/forge50-home.png',fullPage:true});
 await page.locator('[data-action="start"][data-template="chest"]').click();
 const weight=page.locator('[data-set-field="weight"]').first(),reps=page.locator('[data-set-field="reps"]').first(),rir=page.locator('[data-set-field="rir"]').first();
 await weight.fill('20');await reps.fill('10');await rir.fill('2');await page.locator('[data-action="log-set"]').first().click();
 assert.match(await page.locator('#toast').innerText(),/New best/);assert.match(await page.locator('#set-count').innerText(),/^1 \/ /);pass('individual set logging and new-record feedback');
 await page.locator('[data-session-notes]').fill('<img src=x onerror="window.injected=true">');await page.reload();await page.locator('[data-action="open-session"]').first().click();assert.equal(await weight.inputValue(),'20');assert.equal(await page.evaluate(()=>window.injected),undefined);await page.locator('#preferredRest').selectOption('150');await page.locator('[data-action="timer-preferred"]').click();assert.equal(await page.evaluate(()=>Timer.duration),150);pass('draft survives reload and preferred rest timer saves');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/forge50-workout.png',fullPage:false});
 await page.locator('[data-action="rest"]').first().click();assert.equal(await page.evaluate(()=>Timer.duration),180);await page.locator('[data-action="nav"][data-page="home"]').last().click();assert.equal(await page.evaluate(()=>!!Timer.endTime),true);pass('rest timer continues across navigation');
 await page.locator('[data-action="activity"][data-type="cycling"]').click();await page.locator('input[name="minutes"]').fill('35');await page.locator('form[data-form="activity"] button[type="submit"]').click();assert.equal(await page.evaluate(()=>Store.state.sessions.find(s=>s.type==='cycling').minutes),35);pass('cycling log coexists with strength session');
 await page.locator('[data-action="open-session"]').first().click();await page.locator('[data-action="finish"]').click();assert.equal(await page.evaluate(()=>Store.state.cycle.next),'back');await page.reload();await page.locator('[data-action="nav"][data-page="progress"]').last().click();await page.locator('.history-button').filter({hasText:'Chest + triceps'}).click();assert.equal(await page.evaluate(()=>Store.state.sessions.filter(s=>s.type==='lifting').length),1);pass('shortened finish and reopening do not duplicate history');
 await page.locator('[data-session-date]').fill('2026-09-01');await page.locator('[data-session-date]').dispatchEvent('change');assert.equal(await page.evaluate(()=>Store.state.sessions.find(s=>s.type==='lifting').date),'2026-09-01');pass('completed session date is editable');
 await page.locator('[data-action="nav"][data-page="settings"]').last().click();await page.locator('.template-item summary').first().click();await page.locator('.template-item input[name="increment"]').first().fill('0.5');await page.locator('.template-item button[type="submit"]').first().click();assert.equal(await page.evaluate(()=>Store.state.templates.chest.exercises[0].increment),.5);pass('routine settings save without changing past sessions');
 const backup=await page.evaluate(()=>Store.backup());await page.locator('#importFile').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('[data-action="restore"]').click();assert.equal(await page.evaluate(()=>Store.state.sessions.length),2);assert.equal(await page.evaluate(()=>!!localStorage.getItem(Store.RECOVERY_KEY)),true);pass('backup preview, restore and recovery copy');
 await page.locator('[data-action="nav"][data-page="progress"]').last().click();await page.locator('[data-action="month"][data-delta="-1"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/forge50-progress.png',fullPage:true});pass('calendar navigation and mobile progress layout');
 await page.setViewportSize({width:1280,height:900});await page.locator('[data-action="nav"][data-page="home"]').last().click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/forge50-desktop.png',fullPage:true});pass('desktop layout');
 const legacy=await browser.newContext({serviceWorkers:'block'});await legacy.addInitScript(()=>{if(!localStorage.getItem('seeded')){localStorage.setItem('forge50-workoutHistory',JSON.stringify([{date:'2026-09-01',workout:'sunday',percentage:100,duration:45}]));localStorage.setItem('forge50-exerciseLogbook',JSON.stringify({press:[{date:'2026-09-01',day:'sunday',exercise:'Incline Dumbbell Press',weight:20,reps:10}]}));localStorage.setItem('seeded','yes');}});const lp=await legacy.newPage();lp.on('pageerror',e=>errors.push(e.message));await lp.goto(url);await lp.waitForSelector('[data-action="start"]');assert.equal(await lp.evaluate(()=>Store.state.sessions[0].legacy),true);await lp.locator('[data-action="nav"][data-page="progress"]').last().click();await lp.locator('.history-button').first().click();assert.match(await lp.locator('h1').innerText(),/Sunday/);pass('v1.5 automatic migration and imported-history screen');
 const offline=await browser.newContext();const op=await offline.newPage();op.on('pageerror',e=>errors.push(e.message));await op.goto(url);await op.waitForFunction(()=>navigator.serviceWorker.controller);await op.waitForSelector('[data-action="start"]');await offline.setOffline(true);await op.reload();await op.waitForSelector('[data-action="start"]');await op.locator('[data-action="start"][data-template="chest"]').click();await op.locator('[data-action="guide"]').first().click();assert.equal(await op.locator('.forge50-guide-modal.open').count(),1);await op.locator('[data-guide-tab="muscles"]').click();assert.equal(await op.locator('.muscle-figure image').first().evaluate(el=>el.href.baseVal.includes('front.webp')),true);assert.equal(await op.locator('.muscle-mark.primary').count()>0,true);assert.equal(await op.evaluate(async()=>{const r=await fetch('assets/muscle-guides/front.webp');return r.ok&&(await r.blob()).size>10000}),true);await op.locator('.forge50-guide-panel').screenshot({path:'/tmp/forge50-muscles-chest.png'});pass('offline muscle guide shows cached anatomy and highlights');
 assert.deepEqual(await op.evaluate(()=>Object.keys(ForgeDefaults.catalog).filter(id=>!MuscleDiagrams.maps[id]||!MuscleDiagrams.render(id).includes('muscle-mark primary'))),[]);pass('all 32 catalog exercises include highlighted anatomy');
 await offline.setOffline(false);await op.keyboard.press('Escape');updateVersion=true;await op.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await op.waitForSelector('[data-action="apply-update"]');assert.equal(await op.locator('[data-set-field="weight"]').count()>0,true);await op.locator('[data-set-field="weight"]').first().fill('12');await op.locator('[data-action="apply-update"]').click();await op.waitForFunction(()=>document.querySelector('h1')?.textContent==='Your training, your rhythm.');await op.locator('[data-action="open-session"]').first().click();assert.equal(await op.locator('[data-set-field="weight"]').first().inputValue(),'12');pass('update waits for action and draft survives update');
 await page.locator('[data-action="nav"][data-page="home"]').last().click();await page.locator('[data-action="edit-routine"][data-template="back"]').first().click();assert.equal(await page.locator('#templateSelect').inputValue(),'back');const order=page.locator('.template-item summary');const firstBefore=await order.first().innerText();await order.nth(1).click();await page.locator('.template-item').nth(1).locator('[data-action="move-exercise"][data-direction="-1"]').click();assert.notEqual(await order.first().innerText(),firstBefore);await page.locator('[data-action="nav"][data-page="home"]').last().click();await page.locator('[data-action="edit-routine"]').first().click();await page.locator('input[name="includeLegs"]').check();await page.locator('form[data-form="rotation-settings"] button[type="submit"]').click();assert.equal(await page.evaluate(()=>Store.state.preferences.includeLegs),true);await page.locator('[data-action="nav"][data-page="home"]').last().click();assert.equal(await page.locator('.rotation-item').count(),4);pass('home shortcuts reorder routines and optional leg day joins rotation');
 await page.setViewportSize({width:390,height:844});await page.locator('[data-action="start"][data-template="back"]').click();await page.locator('[data-action="toggle-guided"]').click();assert.equal(await page.locator('.guided-card').count(),1);assert.equal(await page.locator('.exercise-card').count(),0);const guidedWeight=page.locator('.guided-set [data-set-field="weight"]'),guidedReps=page.locator('.guided-set [data-set-field="reps"]'),guidedRir=page.locator('.guided-set [data-set-field="rir"]');await guidedWeight.fill('30');await guidedReps.fill('8');await guidedRir.fill('2');await page.locator('.guided-set [data-action="log-set"]').click();assert.equal(await page.evaluate(()=>App.guidedSetIndex),1);assert.equal(await page.evaluate(()=>Timer.duration===Store.session(App.activeId).exercises[0].restSeconds),true);assert.equal(await page.evaluate(()=>Store.session(App.activeId).exercises[0].sets[0].done),true);assert.equal(await page.evaluate(()=>!!Timer.interval),true);await page.locator('#guidedTimerToggle').click();assert.equal(await page.evaluate(()=>!!Timer.interval),false);await page.locator('#guidedTimerToggle').click();assert.equal(await page.evaluate(()=>!!Timer.interval),true);await page.locator('[data-action="guided-next-exercise"]').click();assert.equal(await page.evaluate(()=>App.guidedExerciseIndex),1);assert.equal(await page.evaluate(()=>App.guidedSetIndex),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/forge50-guided.png',fullPage:true});await page.locator('[data-action="toggle-guided"]').click();assert.ok(await page.locator('.exercise-card').count()>1);pass('guided workout logs a set, controls its rest timer, navigates exercises, and returns to full view');
 assert.deepEqual(errors,[]);pass('no uncaught browser errors');console.log(`${checks} browser checks passed.`);
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
