const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..'),errors=[],requests=[];
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.gif':'image/gif','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp'};
const server=http.createServer((req,res)=>{
 const pathname=new URL(req.url,'http://localhost').pathname;requests.push(pathname);
 const relative=decodeURIComponent(pathname).replace(/^\/Forge50\//,'');
 const file=path.resolve(root,relative||'index.html');
 if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end();return;}
 res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(fs.readFileSync(file));
});
let browser,checks=0;const pass=message=>{checks++;console.log('PASS',message);};
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}/Forge50/`;
 browser=await chromium.launch({headless:true,...(process.env.FORGE_BROWSER_PATH?{executablePath:process.env.FORGE_BROWSER_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--use-gl=angle','--use-angle=swiftshader']});
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
 await page.goto(url);await page.waitForFunction(()=>navigator.serviceWorker.controller);await page.waitForLoadState('networkidle');await page.waitForSelector('[data-action="start"]');
 await page.evaluate(()=>{const done=Store.start('chest'),chest=Store.session(done).exercises[0];Store.saveSet(done,chest.id,chest.sets[0].id,{weight:20,reps:10,rir:2,done:true});Store.finish(done);const draft=Store.start('back'),back=Store.session(draft).exercises[0];Store.saveSet(draft,back.id,back.sets[0].id,{weight:35,reps:10,done:false});});
 const before=await page.evaluate(()=>JSON.stringify({...Store.backup(),exportDate:null}));
 await page.evaluate(()=>ExerciseGuides.open('lat-pulldown'));assert.equal(await page.locator('[data-guide-panel="technique"]').isVisible(),true);
 await page.locator('[data-guide-tab="demo"]').click();await page.waitForFunction(()=>document.querySelector('[data-demo-image]').naturalWidth===600);
 assert.ok(!requests.some(file=>file.endsWith('.gif')));assert.equal(await page.locator('[data-demo-toggle]').innerText(),'Play demo');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('.forge50-guide-panel').screenshot({path:'/tmp/forge50-v2.9.1-demo-mobile.png'});
 pass('mobile Demo shows the poster and colour legend without autoplay or any eager GIF request');
 await page.locator('[data-demo-toggle]').click();await page.locator('[data-demo-state="playing"]').waitFor();
 assert.equal(await page.locator('[data-demo-image]').getAttribute('src'),'assets/exercise-demos/gifs/lat-pulldown.gif');
 assert.equal(await page.locator('[data-demo-toggle]').getAttribute('aria-pressed'),'true');
 await page.waitForFunction(async()=>!!(await (await caches.open('forge50-v2.9.1-original-gifs-demos')).match('assets/exercise-demos/gifs/lat-pulldown.gif')));
 await page.locator('[data-demo-toggle]').click();assert.match(await page.locator('[data-demo-image]').getAttribute('src'),/posters\/lat-pulldown\.jpg$/);
 pass('Play loads a real looping GIF, caches it on demand, and Stop restores the static poster');
 await page.locator('[data-demo-toggle]').click();await page.locator('[data-demo-state="playing"]').waitFor();await page.locator('[data-guide-tab="muscles"]').click();
 assert.equal(await page.locator('.muscle-diagram').isVisible(),true);assert.equal(await page.locator('[data-anatomy-mode],canvas,.anatomy-credit').count(),0);assert.equal(await page.locator('.exercise-demo').getAttribute('data-demo-state'),'idle');
 await page.locator('[data-guide-tab="demo"]').click();await page.locator('[data-demo-toggle]').click();await page.locator('[data-demo-state="playing"]').waitFor();
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
 assert.equal(await page.locator('.exercise-demo').getAttribute('data-demo-state'),'idle');await page.evaluate(()=>delete document.hidden);
 await page.locator('[data-demo-toggle]').click();await page.locator('[data-demo-state="playing"]').waitFor();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>ExerciseDemos.current),null);
 pass('leaving Demo, backgrounding, and closing stop playback; Muscles still opens illustrations first');
 await page.evaluate(()=>ExerciseGuides.open('high-row-machine-assisted-pull-up'));await page.locator('[data-guide-tab="demo"]').click();await page.locator('[data-demo-choice]').selectOption('assisted-pull-up');
 assert.match(await page.locator('[data-demo-image]').getAttribute('src'),/posters\/assisted-pull-up\.jpg$/);await page.locator('[data-demo-toggle]').click();await page.locator('[data-demo-state="playing"]').waitFor();
 await page.locator('[data-demo-choice]').selectOption('high-row-machine');assert.equal(await page.locator('.exercise-demo').getAttribute('data-demo-state'),'idle');
 assert.equal(await page.evaluate(()=>ExerciseGuides.current.id),'high-row-machine-assisted-pull-up');
 assert.equal(await page.evaluate(()=>JSON.stringify({...Store.backup(),exportDate:null})),before);
 pass('combined entry changes demonstration only and preserves the catalogue ID and full workout backup');
 const ids=await page.evaluate(()=>Object.keys(ForgeDefaults.catalog));
 for(const id of ids){await page.evaluate(id=>ExerciseGuides.open(id),id);await page.locator('[data-guide-tab="demo"]').click();await page.locator('[data-demo-toggle]').click();await page.locator('[data-demo-state="playing"]').waitFor();assert.equal(await page.locator('[data-demo-image]').evaluate(image=>image.naturalWidth),600,id);await page.locator('[data-demo-toggle]').click();}
 pass('all 39 catalogue guides play valid local demonstrations under /Forge50/');
 await context.setOffline(true);await page.reload();await page.evaluate(()=>ExerciseGuides.open('lat-pulldown'));await page.locator('[data-guide-tab="demo"]').click();await page.locator('[data-demo-toggle]').click();await page.locator('[data-demo-state="playing"]').waitFor();
 assert.equal(await page.evaluate(()=>JSON.stringify({...Store.backup(),exportDate:null})),before);
 pass('a cached GIF plays after an offline reload with the saved draft and backup unchanged');
 await page.evaluate(async()=>{const cache=await caches.open('forge50-v2.9.1-original-gifs-demos');await cache.delete('assets/exercise-demos/gifs/pallof-press.gif');ExerciseGuides.open('pallof-press');});await page.locator('[data-guide-tab="demo"]').click();await page.locator('[data-demo-toggle]').click();await page.locator('[data-demo-state="error"]').waitFor();
 assert.match(await page.locator('[data-demo-image]').getAttribute('src'),/posters\/pallof-press\.jpg$/);await page.waitForFunction(()=>document.querySelector('[data-demo-image]').naturalWidth===600);assert.equal(await page.locator('[data-demo-toggle]').innerText(),'Retry demo');
 await context.setOffline(false);await page.locator('[data-demo-toggle]').click();await page.locator('[data-demo-state="playing"]').waitFor();
 pass('an uncached offline demo keeps its poster and can retry successfully when online');
 await page.evaluate(()=>ExerciseGuides.open('<img src=x onerror="window.injected=true">'));await page.locator('[data-guide-tab="demo"]').click();assert.match(await page.locator('[data-guide-panel="demo"]').innerText(),/No animation/);assert.equal(await page.evaluate(()=>window.injected),undefined);assert.equal(await page.locator('[data-demo-image]').count(),0);
 pass('custom exercise names remain escaped and use the Technique fallback');
 await page.evaluate(()=>ExerciseGuides.open('lat-pulldown'));await page.locator('[data-guide-tab="demo"]').click();await page.setViewportSize({width:1280,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('.forge50-guide-panel').screenshot({path:'/tmp/forge50-v2.9.1-demo-desktop.png'});
 assert.deepEqual(errors,[]);pass('desktop layout stays within the screen and all demo workflows have no uncaught errors');
 console.log(`${checks} exercise-demo browser checks passed.`);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
