const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..'),errors=[],requests=[];
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.gif':'image/gif','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp'};
const server=http.createServer((req,res)=>{
 const pathname=new URL(req.url,'http://localhost').pathname;requests.push(pathname);
 const relative=decodeURIComponent(pathname).replace(/^\/Forge50\//,'');
 const file=path.resolve(root,relative||'index.html');
 if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end();return;}
 res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(fs.readFileSync(file));
});
let browser,checks=0;const pass=message=>{checks++;console.log('PASS',message);};
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}/Forge50/`;
 browser=await chromium.launch({headless:true,...(process.env.FORGE_BROWSER_PATH?{executablePath:process.env.FORGE_BROWSER_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--use-gl=angle','--use-angle=swiftshader']});
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
 const playing=()=>page.locator('[data-demo-state="playing"]').waitFor();
 const snapshot=()=>page.evaluate(()=>JSON.stringify({...Store.backup(),exportDate:null}));
 await page.goto(url);await page.waitForFunction(()=>navigator.serviceWorker.controller);await page.waitForLoadState('networkidle');await page.waitForSelector('[data-action="start"]');
 await page.evaluate(()=>{const done=Store.start('chest'),chest=Store.session(done).exercises[0];Store.saveSet(done,chest.id,chest.sets[0].id,{weight:20,reps:10,rir:2,done:true});Store.finish(done);const draft=Store.start('back'),back=Store.session(draft).exercises[0];Store.saveSet(draft,back.id,back.sets[0].id,{weight:35,reps:10,done:false});});
 const before=await snapshot();
 await page.evaluate(()=>ExerciseGuides.open('lat-pulldown'));assert.equal(await page.locator('[data-guide-panel="technique"]').isVisible(),true);
 assert.ok(!requests.some(file=>file.endsWith('.gif')));assert.equal(await page.locator('[data-demo-toggle]').count(),0);
 pass('opening Guide keeps Technique first and does not eagerly request a GIF');
 await page.locator('[data-guide-tab="demo"]').tap();await playing();
 assert.equal(await page.locator('[data-demo-image]').getAttribute('src'),'assets/exercise-demos/gifs/lat-pulldown.gif');
 assert.equal(await page.getByRole('button',{name:'Play demo',exact:true}).count(),0);assert.equal(await page.locator('[data-demo-retry]').isVisible(),false);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('.forge50-guide-panel').screenshot({path:'/tmp/forge50-v2.9.3-demo-mobile.png'});
 const firstFrame=await page.locator('[data-demo-image]').screenshot();await page.waitForTimeout(800);assert.notDeepEqual(await page.locator('[data-demo-image]').screenshot(),firstFrame);
 await page.waitForFunction(async()=>!!(await (await caches.open('forge50-v2.9.1-original-gifs-demos')).match('assets/exercise-demos/gifs/lat-pulldown.gif')));
 pass('one finger tap on Demo starts a visibly animated GIF with no Play button and caches it on demand');
 await page.locator('[data-guide-tab="muscles"]').tap();assert.equal(await page.locator('.muscle-diagram').isVisible(),true);assert.equal(await page.locator('[data-anatomy-mode],canvas,.anatomy-credit').count(),0);
 assert.equal(await page.locator('.exercise-demo').getAttribute('data-demo-state'),'idle');assert.match(await page.locator('[data-demo-image]').getAttribute('src'),/posters\/lat-pulldown\.jpg$/);
 await page.locator('[data-guide-tab="demo"]').tap();await playing();
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
 assert.equal(await page.locator('.exercise-demo').getAttribute('data-demo-state'),'idle');
 await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await playing();
 await page.locator('[data-guide-tab="technique"]').tap();await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));assert.equal(await page.locator('.exercise-demo').getAttribute('data-demo-state'),'idle');
 await page.locator('[data-guide-tab="demo"]').tap();await playing();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>ExerciseDemos.current),null);
 pass('tab leave/backgrounding stops playback; returning to an active Demo resumes; closing disposes it');
 await page.evaluate(()=>ExerciseGuides.open('high-row-machine-assisted-pull-up'));await page.locator('[data-guide-tab="demo"]').tap();await playing();
 await page.locator('[data-demo-choice]').selectOption('assisted-pull-up');await playing();assert.match(await page.locator('[data-demo-image]').getAttribute('src'),/gifs\/assisted-pull-up\.gif$/);
 await page.locator('[data-demo-choice]').selectOption('high-row-machine');await playing();assert.match(await page.locator('[data-demo-image]').getAttribute('src'),/gifs\/high-row-machine\.gif$/);
 assert.equal(await page.evaluate(()=>ExerciseGuides.current.id),'high-row-machine-assisted-pull-up');assert.equal(await snapshot(),before);
 pass('changing the combined-entry selector automatically plays the chosen GIF without changing its logged ID or backup');
 const ids=await page.evaluate(()=>Object.keys(ForgeDefaults.catalog));
 for(const id of ids){if(id==='hack-squat'){await page.evaluate(id=>ExerciseGuides.open(id),id);await page.locator('[data-guide-tab="demo"]').tap();assert.match(await page.locator('[data-guide-panel="demo"]').innerText(),/No animation/);continue;}await page.evaluate(id=>ExerciseGuides.open(id),id);await page.locator('[data-guide-tab="demo"]').tap();await playing();assert.equal(await page.locator('[data-demo-image]').evaluate(image=>image.naturalWidth),600,id);assert.equal(await page.getByRole('button',{name:'Play demo',exact:true}).count(),0,id);}
 pass('original GIFs play under /Forge50/; Hack Squat has a clear no-animation fallback');
 await context.setOffline(true);await page.reload();await page.evaluate(()=>ExerciseGuides.open('lat-pulldown'));await page.locator('[data-guide-tab="demo"]').tap();await playing();assert.equal(await snapshot(),before);
 pass('a cached GIF starts automatically after an offline reload with completed history, draft and backup unchanged');
 await page.evaluate(async()=>{const cache=await caches.open('forge50-v2.9.1-original-gifs-demos');await cache.delete('assets/exercise-demos/gifs/pallof-press.gif');ExerciseGuides.open('pallof-press');});await page.locator('[data-guide-tab="demo"]').tap();await page.locator('[data-demo-state="error"]').waitFor();
 assert.match(await page.locator('[data-demo-image]').getAttribute('src'),/posters\/pallof-press\.jpg$/);await page.waitForFunction(()=>document.querySelector('[data-demo-image]').naturalWidth===600);assert.equal(await page.locator('[data-demo-retry]').isVisible(),true);
 await context.setOffline(false);await page.locator('[data-demo-retry]').tap();await playing();assert.equal(await page.locator('[data-demo-retry]').isVisible(),false);
 pass('an uncached offline demo keeps the poster and shows Retry only on failure');
 await page.evaluate(()=>ExerciseGuides.open('<img src=x onerror="window.injected=true">'));await page.locator('[data-guide-tab="demo"]').tap();assert.match(await page.locator('[data-guide-panel="demo"]').innerText(),/No animation/);assert.equal(await page.evaluate(()=>window.injected),undefined);assert.equal(await page.locator('[data-demo-image]').count(),0);
 pass('custom exercise names stay escaped and use the Technique fallback');
 const slow=await browser.newContext({serviceWorkers:'block',viewport:{width:390,height:844},hasTouch:true}),sp=await slow.newPage();sp.on('pageerror',error=>errors.push(error.message));
 let release,started,finished;const gate=new Promise(resolve=>{release=resolve;}),began=new Promise(resolve=>{started=resolve;}),done=new Promise(resolve=>{finished=resolve;});
 await sp.route('**/lat-pulldown.gif',async route=>{started();await gate;try{await route.fulfill({contentType:'image/gif',body:fs.readFileSync(path.join(root,'assets/exercise-demos/gifs/lat-pulldown.gif'))});}catch{/* Navigation may cancel the old request. */}finally{finished();}});
 await sp.goto(url);await sp.evaluate(()=>ExerciseGuides.open('lat-pulldown'));await sp.locator('[data-guide-tab="demo"]').tap();await began;assert.equal(await sp.locator('.exercise-demo').getAttribute('data-demo-state'),'loading');
 await sp.locator('[data-guide-tab="technique"]').tap();release();await done;await sp.waitForLoadState('networkidle');assert.equal(await sp.locator('.exercise-demo').getAttribute('data-demo-state'),'idle');assert.match(await sp.locator('[data-demo-image]').getAttribute('src'),/posters\/lat-pulldown\.jpg$/);await slow.close();
 pass('leaving a slowly loading Demo prevents a late response from restarting it');
 await page.evaluate(()=>ExerciseGuides.open('lat-pulldown'));await page.locator('[data-guide-tab="demo"]').tap();await playing();await page.setViewportSize({width:1280,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('.forge50-guide-panel').screenshot({path:'/tmp/forge50-v2.9.3-demo-desktop.png'});
 assert.deepEqual(errors,[]);pass('desktop layout stays within the screen with no uncaught errors');
 console.log(`${checks} exercise-demo browser checks passed.`);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
