// Run: node tests/store.test.cjs (no packages needed)
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');let passed=0;
function make(seed={}){const db=new Map(Object.entries(seed));const c={console,crypto,Date,localStorage:{getItem:k=>db.get(k)??null,setItem:(k,v)=>db.set(k,String(v)),removeItem:k=>db.delete(k)}};c.window=c;vm.createContext(c);for(const f of ['data.js','js/exercise-catalog-expansion.js','js/store.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c);c.Store.init();return {S:c.Store,db,storage:c.localStorage};}
function test(name,fn){fn();passed++;console.log('PASS',name);}
function logged(S,type='chest',date){const id=S.start(type,date),e=S.session(id).exercises[0],set=e.sets[0];S.saveSet(id,e.id,set.id,{weight:20,reps:10,rir:2,done:true});return id;}
test('separate sessions and cycling coexist on one date',()=>{const {S}=make();const a=logged(S),b=logged(S,'back');S.activity('cycling',S.today(),30,'easy');assert.equal(S.session(a).exercises[0].sets[0].done,true);assert.equal(S.session(b).exercises[0].sets[0].done,true);assert.equal(S.state.sessions.length,3);});
test('finish is idempotent; shoulders wrap; legs preserve place',()=>{const {S}=make();const a=logged(S);S.finish(a);assert.equal(S.state.cycle.next,'back');S.finish(a);assert.equal(S.state.sessions.length,1);assert.equal(S.state.cycle.next,'back');S.finish(logged(S,'legs'));assert.equal(S.state.cycle.next,'back');S.finish(logged(S,'shoulders'));assert.equal(S.state.cycle.next,'chest');});
test('optional leg day joins the rotation after shoulders and can be removed',()=>{const {S}=make();S.change(s=>{s.preferences.includeLegs=true;});S.finish(logged(S,'chest'));assert.equal(S.state.cycle.next,'back');S.finish(logged(S,'back'));assert.equal(S.state.cycle.next,'shoulders');S.finish(logged(S,'shoulders'));assert.equal(S.state.cycle.next,'legs');S.finish(logged(S,'legs'));assert.equal(S.state.cycle.next,'chest');S.change(s=>{s.cycle.next='legs';});S.change(s=>{s.preferences.includeLegs=false;s.cycle.next='chest';});assert.equal(S.state.cycle.next,'chest');});
test('timer and screen preferences save while older backups remain compatible',()=>{const {S}=make();const old=S.backup();delete old.state.preferences;assert.doesNotThrow(()=>S.readBackup(old));const previous=S.backup();delete previous.state.preferences.keepAwake;assert.doesNotThrow(()=>S.readBackup(previous));S.change(s=>{s.preferences.preferredRestSeconds=150;s.preferences.keepAwake=true;});assert.equal(S.readBackup(S.backup()).preferences.preferredRestSeconds,150);assert.equal(S.readBackup(S.backup()).preferences.keepAwake,true);const bad=S.backup();bad.state.preferences.preferredRestSeconds=0;assert.throws(()=>S.readBackup(bad));bad.state.preferences.preferredRestSeconds=120;bad.state.preferences.keepAwake='yes';assert.throws(()=>S.readBackup(bad));});
test('unfinished session resumes without duplication',()=>{const {S}=make();const a=S.start('chest');assert.equal(S.start('chest'),a);});
test('cycling and rest do not advance sequence',()=>{const {S}=make();const plan=JSON.stringify(S.state.cycle);S.activity('cycling',S.today(),20,'moderate');S.activity('rest',S.today(),0,'easy');assert.equal(JSON.stringify(S.state.cycle),plan);});
test('zero load accepted; negative and fractional reps rejected atomically',()=>{const {S}=make();const id=S.start('chest'),e=S.session(id).exercises[0],set=e.sets[0];S.saveSet(id,e.id,set.id,{weight:0,reps:12,done:true});assert.throws(()=>S.saveSet(id,e.id,set.id,{weight:-2}));assert.throws(()=>S.saveSet(id,e.id,set.id,{reps:2.5}));assert.equal(S.session(id).exercises[0].sets[0].weight,0);});
test('new best set detected before saving',()=>{const {S}=make();const id=logged(S),e=S.session(id).exercises[0];assert.equal(S.saveSet(id,e.id,e.sets[1].id,{weight:22,reps:10,rir:2,done:true}),true);assert.equal(S.best(e.id,e.weightMode).weight,22);});
test('set volume sums actual entries and dumbbell pairs',()=>{const {S}=make();const id=logged(S),e=S.session(id).exercises[0];S.saveSet(id,e.id,e.sets[1].id,{weight:20,reps:9,done:true});S.finish(id);assert.equal(S.stats(7).sets,2);assert.equal(S.stats(7).volume,760);assert.equal(S.stats(7).muscles.Chest,2);});
test('session-only swap preserves the saved routine and rejects unrelated or duplicate exercises',()=>{const {S}=make(),id=S.start('chest'),old=S.session(id).exercises[0],template=JSON.stringify(S.state.templates.chest);const options=S.swapOptions(id,old.id);assert.ok(options.some(e=>e.id==='cable-chest-press'));assert.ok(options.every(e=>e.muscle==='Chest'&&!S.session(id).exercises.some(x=>x.id===e.id)));const before=JSON.stringify(S.session(id));assert.throws(()=>S.swapExercise(id,old.id,'lat-pulldown'));assert.equal(JSON.stringify(S.session(id)),before);const idx=S.swapExercise(id,old.id,'cable-chest-press');assert.equal(idx,0);assert.equal(S.session(id).exercises[0].id,'cable-chest-press');assert.equal(S.session(id).exercises[0].sets.length,old.sets.length);assert.equal(JSON.stringify(S.state.templates.chest),template);assert.throws(()=>S.swapExercise(id,S.session(id).exercises[1].id,'cable-chest-press'));assert.equal(S.readBackup(S.backup()).sessions[0].exercises[0].id,'cable-chest-press');});
test('swapping after logged sets preserves those sets and counts only actual work by muscle',()=>{const {S}=make(),id=S.start('back'),old=S.session(id).exercises[0],originalCount=old.sets.length;S.saveSet(id,old.id,old.sets[0].id,{weight:40,reps:9,rir:2,done:true});const idx=S.swapExercise(id,old.id,'straight-arm-pulldown');const session=S.session(id);assert.equal(idx,1);assert.equal(session.exercises[0].sets.length,1);assert.equal(session.exercises[0].sets[0].done,true);assert.equal(session.exercises[1].sets.length,originalCount-1);assert.equal(session.exercises[1].muscle,'Back');S.saveSet(id,session.exercises[1].id,session.exercises[1].sets[0].id,{weight:25,reps:12,rir:2,done:true});S.finish(id);const back=S.muscleStats(7).find(g=>g.muscle==='Back');assert.equal(back.sets,2);assert.equal(back.exercises[old.id].sets,1);assert.equal(back.exercises['straight-arm-pulldown'].sets,1);assert.equal(S.stats(7).muscles.Back,2);assert.equal(S.swapOptions(id,old.id).length,0);});
test('muscle statistics compare equal date windows and exclude drafts and cycling',()=>{const {S}=make(),id=logged(S);S.finish(id);const old=S.start('back',S.addDays(S.today(),-8)),e=S.session(old).exercises[0];S.saveSet(old,e.id,e.sets[0].id,{weight:30,reps:9,rir:2,done:true});S.finish(old);S.start('shoulders');S.activity('cycling',S.today(),30,'easy');const groups=S.muscleStats(7),chest=groups.find(g=>g.muscle==='Chest'),back=groups.find(g=>g.muscle==='Back');assert.equal(chest.sets,1);assert.equal(chest.previous,0);assert.equal(back.sets,0);assert.equal(back.previous,1);assert.equal(back.lastDate,null);});
test('reopening and editing completed workout does not advance cycle',()=>{const {S}=make();const id=logged(S);S.finish(id);const plan=JSON.stringify(S.state.cycle);S.patchSession(id,s=>s.date=S.addDays(S.today(),-3));assert.equal(JSON.stringify(S.state.cycle),plan);assert.equal(S.state.sessions.length,1);});
test('cycle dates use calendar days',()=>{const {S}=make();assert.equal(S.addDays('2026-03-28',2),'2026-03-30');assert.equal(S.validDate('2026-02-30'),false);assert.throws(()=>S.start('chest','2026-02-30'));});
test('template changes do not rewrite session snapshots',()=>{const {S}=make();const id=S.start('chest'),before=S.session(id).exercises[0].reps;S.change(s=>s.templates.chest.exercises[0].reps='1-2');assert.equal(S.session(id).exercises[0].reps,before);});
test('expanded plan keeps nine chest exercises, eight on other upper-body days and the agreed muscle groups',()=>{const {S}=make();const ids=key=>Array.from(S.state.templates[key].exercises,e=>e.id);assert.deepEqual(ids('chest'),['incline-dumbbell-press','incline-dumbbell-fly','flat-dumbbell-press','machine-lower-chest-press','high-to-low-cable-fly','low-to-high-cable-fly','rope-triceps-pushdown','overhead-cable-triceps-extension','triceps-extension-machine']);assert.deepEqual(ids('back'),['lat-pulldown','chest-supported-row','high-row-machine','seated-cable-row','single-arm-cable-row','cable-curl','ez-bar-curl','incline-dumbbell-curl']);assert.deepEqual(ids('shoulders'),['dumbbell-shoulder-press','machine-lateral-raise','dumbbell-lateral-raise','reverse-pec-deck','high-face-pull','high-row-machine','cable-crunch','pallof-press']);assert.deepEqual(['chest','back','shoulders'].map(k=>S.state.templates[k].exercises.reduce((n,e)=>n+e.sets,0)),[26,22,23]);assert.equal(S.state.templates.shoulders.title,'Shoulders + upper back + abs');});
test('applying expanded plan preserves snapshots, leg day, schedule, and backup',()=>{const {S,db}=make();const id=logged(S),draft=S.start('back'),savedSession=JSON.stringify(S.session(id)),savedDraft=JSON.stringify(S.session(draft));S.change(s=>{s.routinePlan='upper-body-2026-09';s.templates.chest.exercises[0].sets=2;s.templates.legs.exercises[0].sets=5;s.cycle.next='back';s.cycle.nextDate=S.addDays(S.today(),2);});const previous=JSON.stringify(S.state);const before=S.backup();S.applyRoutinePlan();assert.equal(S.state.templates.chest.exercises[0].sets,4);assert.equal(S.state.templates.legs.exercises[0].sets,5);assert.equal(S.state.cycle.next,'back');assert.equal(S.state.cycle.nextDate,S.addDays(S.today(),2));assert.equal(JSON.stringify(S.session(id)),savedSession);assert.equal(JSON.stringify(S.session(draft)),savedDraft);assert.equal(S.state.routinePlan,'upper-body-2026-09-expanded');assert.equal(S.readBackup(before).templates.chest.exercises[0].sets,2);assert.equal(S.readBackup(S.backup()).templates.chest.exercises[0].sets,4);assert.notEqual(db.get(S.KEY),previous);});
test('optional sets may be skipped without marking a completed workout shortened',()=>{const {S}=make(),id=S.start('chest'),session=S.session(id);for(const e of session.exercises.filter(x=>!x.optional))for(const set of e.sets)S.saveSet(id,e.id,set.id,{weight:10,reps:10,rir:2,done:true});S.finish(id);assert.equal(S.session(id).partial,false);assert.ok(S.session(id).exercises.some(e=>e.optional&&e.sets.every(x=>!x.done)));});
test('progression uses completed sets, actual effort and per-exercise increment',()=>{const {S}=make();const id=S.start('chest');let e=S.session(id).exercises[0];S.patchSession(id,s=>s.exercises[0].increment=0.5);e=S.session(id).exercises[0];for(const x of e.sets)S.saveSet(id,e.id,x.id,{weight:20,reps:Number(e.reps.split('-')[1]),rir:2,done:true});S.finish(id);S.activity('cycling',S.today(),30,'easy');const other=S.start('chest');const current=S.session(other).exercises[0];current.increment=.5;assert.equal(S.recommend(current,other).sets[0].weight,20.5);S.patchSession(id,s=>s.exercises[0].sets[0].rir=null);assert.equal(S.recommend(current,other).ready,false);});
test('backup restore validates before mutation and keeps recovery copy',()=>{const {S,db}=make();logged(S);const backup=S.backup();const bad=S.copy(backup);bad.state.sessions[0].date='invalid';const before=db.get(S.KEY);assert.throws(()=>S.readBackup(bad));assert.equal(db.get(S.KEY),before);S.restore(S.readBackup(backup));assert.equal(db.get(S.RECOVERY_KEY),before);});
test('unsafe imported identifiers rejected',()=>{const {S}=make();logged(S);const b=S.backup();b.state.sessions[0].id='x" onclick="alert(1)';assert.throws(()=>S.readBackup(b));});
test('legacy data retained, duplicate history collapsed, no sets invented',()=>{const legacy={history:[{date:'2026-09-01',workout:'sunday',percentage:100},{date:'2026-09-01',workout:'sunday',percentage:100}],exerciseLogs:{sunday_press:[{day:'sunday',date:'2026-09-01',exercise:'Incline Dumbbell Press',weight:20,reps:10,notes:'<b>literal</b>'}]},currentProgress:{},personalRecords:{old:{weightPR:30}}};const {S}=make({'forge50-workoutHistory':JSON.stringify(legacy.history),'forge50-exerciseLogbook':JSON.stringify(legacy.exerciseLogs),'forge50-personalRecords':JSON.stringify(legacy.personalRecords)});assert.equal(S.state.sessions.length,1);assert.equal(S.state.sessions[0].exercises[0].sets.length,1);assert.equal(S.state.legacy.history.length,2);assert.equal(S.state.legacy.personalRecords.old.weightPR,30);assert.equal(S.stats(28).sets,0);});
test('corrupt saved data is not overwritten',()=>{const db=new Map([['forge50-v2','invalid']]);const c={window:null,crypto,Date,localStorage:{getItem:k=>db.get(k)||null,setItem:(k,v)=>db.set(k,v)}};c.window=c;vm.createContext(c);for(const f of ['data.js','js/exercise-catalog-expansion.js','js/store.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c);assert.throws(()=>c.Store.init());assert.equal(db.get('forge50-v2'),'invalid');});
test('storage failure leaves in-memory state unchanged',()=>{const {S,storage,db}=make();const initial=JSON.stringify(S.state),saved=db.get(S.KEY);storage.setItem=()=>{throw new Error('quota');};assert.throws(()=>S.start('chest'));assert.equal(JSON.stringify(S.state),initial);assert.equal(db.get(S.KEY),saved);});
console.log(`${passed} checks passed.`);
